import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Image />
          <Link href='/'>Home</Link>
          <Link href='/events'>Events</Link>
          <Link href='/about-us'>About us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        <Link href='#'>
          <img src="#" alt="" />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde culpa, fuga ab, optio voluptates accusamus porro corrupti excepturi aspernatur.
          </p>
        </Link>
        <Link href='#'>
          <img src="#" alt="" />
          <h2>Events in los angeles</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde culpa, fuga ab, optio voluptates accusamus porro corrupti excepturi aspernatur.
          </p>
        </Link>
        <Link href='#'>
          <img src="#" alt="" />
          <h2>Events in barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde culpa, fuga ab, optio voluptates accusamus porro corrupti excepturi aspernatur.
          </p>
        </Link>
        <Link href='#'>
          <img src="#" alt="" />
          <h2>Events in azna</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde culpa, fuga ab, optio voluptates accusamus porro corrupti excepturi aspernatur.
          </p>
        </Link>
      </main>
      <footer></footer>
    </>
  )
}
