import Head from 'next/head'
import MainHomePage from '../src/Components/MainHomePage'


export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHomePage data={data}/>
    </>
  )
}


export const getServerSideProps = async () => {
  const {events_categories} = await import('/data/data.json')

  return {
    props:{
      data: events_categories,
    }
  }
}